[store]
brands=[
    'farfetch-male-yeezy',
    'farfetch-female-yeezy',
    'farfetch-male-jordan',
    'farfetch-female-jordan',
    'farfetch-female-stella',
    'farfetch-female-adidas',
    'farfetch-female-nike-x-off-white',
    'farfetch-female-nike',
    'farfetch-male-adidas-pw',
    'farfetch-male-stella',
    'farfetch-male-adidas',
    'farfetch-male-nike',
    'farfetch-male-nike-x-off-white',
]